version: "3"
services:

#  MySQL Service
  mysql-db:
    image: mysql:5.7.33
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  #spring Service
  spring-boot-app:
    image: spring-boot-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/employee_db?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 8181:8181
      - 4444:4444
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
